"""Import the Trunks artwork and enable the cutout in the existing level."""
import unreal
from pathlib import Path
import json
project=Path(unreal.Paths.project_dir()).resolve()
folder='/Game/Toy/Actions'
unreal.EditorAssetLibrary.make_directory(folder)
task=unreal.AssetImportTask()
task.set_editor_property('filename',str(project/'Art/Actions/TrunksActions.png'))
task.set_editor_property('destination_path',folder)
task.set_editor_property('destination_name','T_ActionPoses')
task.set_editor_property('automated',True)
task.set_editor_property('replace_existing',True)
task.set_editor_property('save',True)
unreal.AssetToolsHelpers.get_asset_tools().import_asset_tasks([task])
texture=unreal.load_asset(folder+'/T_ActionPoses')
assert texture
texture.set_editor_property('srgb',True)
texture.set_editor_property('max_texture_size',2048)
texture.set_editor_property('address_x',unreal.TextureAddress.TA_CLAMP)
texture.set_editor_property('address_y',unreal.TextureAddress.TA_CLAMP)
unreal.EditorAssetLibrary.save_loaded_asset(texture)
for i in range(6):
    material=unreal.load_asset(folder+'/M_Action'+str(i))
    if not material:
        material=unreal.AssetToolsHelpers.get_asset_tools().create_asset('M_Action'+str(i),folder,unreal.Material,unreal.MaterialFactoryNew())
    else:
        unreal.MaterialEditingLibrary.delete_all_material_expressions(material)
    material.set_editor_property('blend_mode',unreal.BlendMode.BLEND_MASKED)
    material.set_editor_property('shading_model',unreal.MaterialShadingModel.MSM_UNLIT)
    material.set_editor_property('two_sided',True)
    material.set_editor_property('opacity_mask_clip_value',0.5)
    sample=unreal.MaterialEditingLibrary.create_material_expression(material,unreal.MaterialExpressionTextureSample,-500,0)
    sample.set_editor_property('texture',texture)
    uv=unreal.MaterialEditingLibrary.create_material_expression(material,unreal.MaterialExpressionTextureCoordinate,-1000,0)
    uv.set_editor_property('u_tiling',1.0/3.0)
    uv.set_editor_property('v_tiling',-0.5)
    offset=unreal.MaterialEditingLibrary.create_material_expression(material,unreal.MaterialExpressionConstant2Vector,-1000,120)
    offset.set_editor_property('r',(i%3)/3.0)
    offset.set_editor_property('g',(i//3+1)/2.0)
    add=unreal.MaterialEditingLibrary.create_material_expression(material,unreal.MaterialExpressionAdd,-750,0)
    assert unreal.MaterialEditingLibrary.connect_material_expressions(uv,'',add,'A')
    assert unreal.MaterialEditingLibrary.connect_material_expressions(offset,'',add,'B')
    assert unreal.MaterialEditingLibrary.connect_material_expressions(add,'',sample,'UVs')
    key=unreal.MaterialEditingLibrary.create_material_expression(material,unreal.MaterialExpressionCustom,-250,150)
    key.set_editor_property('code','return 1.0-step(0.15, Color.g-max(Color.r,Color.b));')
    key.set_editor_property('output_type',unreal.CustomMaterialOutputType.CMOT_FLOAT1)
    key.set_editor_property('description','Remove chroma green background; keep black outlines and clothing')
    input=unreal.CustomInput()
    input.set_editor_property('input_name','Color')
    key.set_editor_property('inputs',[input])
    assert unreal.MaterialEditingLibrary.connect_material_expressions(sample,'RGB',key,'Color')
    assert unreal.MaterialEditingLibrary.connect_material_property(sample,'RGB',unreal.MaterialProperty.MP_EMISSIVE_COLOR)
    assert unreal.MaterialEditingLibrary.connect_material_property(key,'',unreal.MaterialProperty.MP_OPACITY_MASK)
    unreal.MaterialEditingLibrary.recompile_material(material)
    unreal.EditorAssetLibrary.save_loaded_asset(material)
(project/'Saved/Verification/actions_assets.json').write_text(json.dumps({'assets_pass':True,'materials':6,'texture':texture.get_path_name()},indent=2))
