"""Import the Trunks artwork and enable the cutout in the existing level."""
import unreal
from pathlib import Path
import json
project=Path(unreal.Paths.project_dir()).resolve()
folder='/Game/Toy/Cutout'
unreal.EditorAssetLibrary.make_directory(folder)
task=unreal.AssetImportTask()
task.set_editor_property('filename',str(project/'Art/Trunks/TrunksCutoutGreen.png'))
task.set_editor_property('destination_path',folder)
task.set_editor_property('destination_name','T_TrunksCutout')
task.set_editor_property('automated',True)
task.set_editor_property('replace_existing',True)
task.set_editor_property('save',True)
unreal.AssetToolsHelpers.get_asset_tools().import_asset_tasks([task])
texture=unreal.load_asset(folder+'/T_TrunksCutout')
assert texture
texture.set_editor_property('srgb',True)
texture.set_editor_property('max_texture_size',1024)
texture.set_editor_property('address_x',unreal.TextureAddress.TA_CLAMP)
texture.set_editor_property('address_y',unreal.TextureAddress.TA_CLAMP)
unreal.EditorAssetLibrary.save_loaded_asset(texture)
material=unreal.load_asset(folder+'/M_TrunksCutout')
if not material:
    material=unreal.AssetToolsHelpers.get_asset_tools().create_asset('M_TrunksCutout',folder,unreal.Material,unreal.MaterialFactoryNew())
else:
    unreal.MaterialEditingLibrary.delete_all_material_expressions(material)
material.set_editor_property('blend_mode',unreal.BlendMode.BLEND_MASKED)
material.set_editor_property('shading_model',unreal.MaterialShadingModel.MSM_UNLIT)
material.set_editor_property('two_sided',True)
material.set_editor_property('opacity_mask_clip_value',0.5)
sample=unreal.MaterialEditingLibrary.create_material_expression(material,unreal.MaterialExpressionTextureSample,-500,0)
sample.set_editor_property('texture',texture)
uv=unreal.MaterialEditingLibrary.create_material_expression(material,unreal.MaterialExpressionTextureCoordinate,-1000,0)
uv.set_editor_property('v_tiling',-1.0)
offset=unreal.MaterialEditingLibrary.create_material_expression(material,unreal.MaterialExpressionConstant2Vector,-1000,120)
offset.set_editor_property('r',0.0)
offset.set_editor_property('g',1.0)
add=unreal.MaterialEditingLibrary.create_material_expression(material,unreal.MaterialExpressionAdd,-750,0)
assert unreal.MaterialEditingLibrary.connect_material_expressions(uv,'',add,'A')
assert unreal.MaterialEditingLibrary.connect_material_expressions(offset,'',add,'B')
assert unreal.MaterialEditingLibrary.connect_material_expressions(add,'',sample,'UVs')
key=unreal.MaterialEditingLibrary.create_material_expression(material,unreal.MaterialExpressionCustom,-250,150)
key.set_editor_property('code','return 1.0-step(0.15, Color.g-max(Color.r,Color.b));')
key.set_editor_property('output_type',unreal.CustomMaterialOutputType.CMOT_FLOAT1)
key.set_editor_property('description','Remove chroma green background; keep black outlines and clothing')
input=unreal.CustomInput()
input.set_editor_property('input_name','Color')
key.set_editor_property('inputs',[input])
assert unreal.MaterialEditingLibrary.connect_material_expressions(sample,'RGB',key,'Color')
assert unreal.MaterialEditingLibrary.connect_material_property(sample,'RGB',unreal.MaterialProperty.MP_EMISSIVE_COLOR)
assert unreal.MaterialEditingLibrary.connect_material_property(key,'',unreal.MaterialProperty.MP_OPACITY_MASK)
unreal.MaterialEditingLibrary.recompile_material(material)
unreal.EditorAssetLibrary.save_loaded_asset(material)
levels=unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
actors=unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
levels.load_level('/Game/Toy/Maps/ToyLab')
count=0
for actor in actors.get_all_level_actors():
    if not isinstance(actor,unreal.ToyCharacter):continue
    actor.set_editor_property('use_image_cutout',True)
    actor.set_editor_property('enable_secondary_physics',False)
    actor.set_actor_label('TRUNKS - IMAGE CUTOUT - edit Toy settings')
    mesh=actor.get_editor_property('mesh')
    mesh.set_visibility(False,True)
    cutout=actor.get_editor_property('image_cutout')
    cutout.set_material(0,material)
    cutout.set_visibility(True)
    cutout.set_relative_scale3d(unreal.Vector(1.2161,1.8,1))
    cutout.set_relative_rotation(unreal.Rotator(0,0,90),False,True)
    actor.get_editor_property('placeholder_label').set_text('TRUNKS - IMAGE CUTOUT')
    count+=1
assert count==1
levels.save_current_level()
unreal.EditorAssetLibrary.save_directory(folder)
(project/'Saved/Verification/cutout_assets.json').write_text(json.dumps({'cutout_assets_pass':True,'actor_count':count,'texture':texture.get_path_name(),'material':material.get_path_name(),'material_masked':True,'source_alpha':False,'background_removal':'Chroma-green mask in Unreal material','source':'Art/Trunks/TrunksCutoutGreen.png'},indent=2))
unreal.log('TOY CUTOUT ASSETS PASS')
